language: android
sudo: false
jdk: oraclejdk8

env:
  global:
    - EMULATOR_API=22 # 24 has some issues, probably some overlayed window
    - EMULATOR_ABI=x86_64 # seems to work with emulator v29.
    - EMULATOR_TAG=default # can be google_apis
    - PATH=$ANDROID_HOME:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - doc-28

install:
  # Setup
  - echo $ANDROID_HOME # We assume this is correctly set when setting path
  - sdkmanager --list || true # Look at the packages
  - echo yes | sdkmanager "tools" # Ensure tools is updated
  - echo yes | sdkmanager "emulator" # Ensure emulator is present

  # Install emulator
  # The channel=4 line looks into canary which brings in v29.
  # The previous version v28 was broken:
  # https://travis-ci.community/t/android-emulators-not-starting-for-the-last-few-days-late-march-2019/2871/11?u=mikehardy
  - export EMULATOR="system-images;android-$EMULATOR_API;$EMULATOR_TAG;$EMULATOR_ABI"
  - echo yes | sdkmanager "platforms;android-$EMULATOR_API" # Install sdk for the emulator
  - echo yes | sdkmanager --channel=4 "$EMULATOR" # Install system image
  - sdkmanager --list || true # Check everything is updated

  # Create adn start emulator
  - echo no | avdmanager create avd -n test -k "$EMULATOR" -f # Create emulator virtual device
  - which emulator # ensure we are using the right emulator ($ANDROID_HOME/emulator/emulator)
  - emulator -avd test -no-window -no-accel -no-snapshot -memory 2048 -writable-system & # Launch
  - adb wait-for-device # Wait for adb process
  - adb remount # Mount as writable

before_script:
  # Wait for emulator
  - android-wait-for-emulator # Wait for emulator ready to interact
  # Unlock and configure logs.
  # Would be great to use -v color to adb logcat but looks not supported on travis.
  - sleep 20 # Sleep 20 seconds just in case
  - adb shell input keyevent 82 & # Dispatch unlock event

script:
  - ./gradlew clean
  - ./gradlew test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
